# Generated by Django 4.2.30 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinatura",
            name="mes_atual",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assinatura",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
